spring:
  main:
    banner-mode: "off"
  application:
    name: "filmorate"
server:
  port: 8080

filmorate:
  endpoints:
    users: "/users"
    films: "/films"
  film:
    popular:
      count: 10

  logging:
    level:
      org:
        zalando:
          logbook: TRACE